name: monitoring

volumes:
  prometheus_data:
  grafana_data: 

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-${HOSTNAME}
      #    hostname: rp3
      #    domainname: net0
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_data:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-${HOSTNAME}
      #    hostname: rp3
      #    domainname: net0
    restart: unless-stopped
    ports:
      - 3000:3000
    user: "1000"
    volumes:
      - ./grafana_data/grafana:/var/lib/grafana
        #    environment:
        #      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
        #      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
        #      - GF_USERS_ALLOW_SIGN_UP=false

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter-${HOSTNAME}
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor-${HOSTNAME}
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
