global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: 49house
  static_configs:
  - targets:
    - 49house.net0:9100
- job_name: le8450
  static_configs:
  - targets:
    - le8450.net0:9100
- job_name: node_exporter-rp3
  static_configs:
  - targets:
    - node_exporter-rp3:9100
- job_name: prometheus
  static_configs:
    - targets:
      - prometheus-rp3:9090
- job_name: grafana_metrics-rp3
  static_configs:
    - targets:
      - grafana-rp3:3000
- job_name: cadvisor-rp3
  static_configs:
    - targets:
      - cadvisor-rp3:8080
